---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-secret
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: AgCFcLEB/uf76TUTFEjzfUoMgXEU6B/byG5BNOS51nGywgPVKOKGITfW92JDnt2La6d93z2hG7j+9VGL2npyPDs5U3EFqAtySkRreHHX6XUlErIFcBBper0C8RgmjJkDHJUnwdTz+3OJro//lrtxYILjTEvyWyRVDEhgYHRF/K/GANJIUu1cx31xcYsZEiQpaxsqYJHVD8uhsvSoPJGU/uZ9Gis3OG5mUHytCkKNkbSzaHvCsDFFCkQJmkorTcUaldViqfjH7b4+ei5BQEUcg2v05PP+mgT3SlRNgsA6BwxWDFK3fFyt6x3yR4r8Z8wWOGAgmCLYDZBPQpyM/ugyxutubSpAYxhLtAcMI2sPJ/ZoS9csFuDPlbiNuLVXes+gojdhFobVydjzE8XndW6ZktU3Snt7f+cYUqP3ROe08RBwfc8O1pBh8e9XMl78KClBPGtATNB2yqBYjVCfxpeql0r7jnQZ49Ou8moAgG98UATYnVrDrjiiyoxiKYaVIZgYlqvkXqY8rW0bHcGcH/8bpAny6LqicEwfKeYYfL6H63SQuPZUFW0Hg4N8tACkvry3gfJ5HRsL0pnip9NNTRdKf+ZeTp1EY6t/P6/pyuAOFCLjRI4FcG5qbY2uQlzk29HrNjbmbGl6DdsZG9N21tVAtmIQEax4KDJIgcQ06AkX3tfkXziveDjU5g7Lr/6kbN25/vLJbaFs5oH0CXM84NcfgW5QbuWruWRzc/ywqtfGfkn13/Cbh5Znd1FkI8syIA7TrysYKVlhEs4hdjk8FMTwrYYdc2gy7y8q3GfSfFt2ia88gdZNhlkhCsni8xFbBOMZxowmTQDlv2ATwy2xB3cYwDWW594e6aXXl2FmFqm9rPytj9KxQBvnK7FhAptNpfnolcXXa/TxiZ6Dhv/XElyJ62XpRsCrpOIJqCzVEJlVKJ9X5XNptCoDJXVfn4PLmzfrJ5BhiFTZxxZIgOdVWqVxG4Fn9WGPzp/V02a4WoXZ6a9Baw==
  template:
    metadata:
      name: dockerhub-secret
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
